---
- name: clone_roles
  hosts: all
  become: true
  vars:
    git_repository: "https://github.com/gajdamariusz84/Ansible_roles.git"
    git_branch: "master"
  tasks:
    - name: create /etc/ansible/roles dir
      file:
        path: /etc/ansible/roles
        state: directory
        mode: '0755'
    - name: checkout git repo
      git:
        repo: "{{ git_repository }}"
        dest: "/etc/ansible/roles"
        version: "{{ git_branch }}"